#!/bin/sh
i=0
touch /home/mehdi/temp/drivers.list /home/mehdi/temp/ports.list
sed "s/.*=//" /sys/class/tty/ttyUSB*/device/uevent > /home/mehdi/temp/drivers.list
sed "s/.*://" /sys/class/tty/ttyUSB*/dev > /home/mehdi/temp/ports.list
configlist=$(paste -d "_" /home/mehdi/temp/drivers.list /home/mehdi/temp/ports.list)
for device in $configlist
do
	configfile=/etc/minirc."$device"
	[ -f $configfile ] && chown mehdi $configfile && sed -n "s/USB*?/USB$i/" $configfile || sudo touch $configfile && sudo chown mehdi $configfile && echo "pu port             /dev/ttyUSB$i" > $configfile || echo "file not created"
	((i=i+1))
done

chosen="$(echo "$configlist" | dmenu -i -p "Connect to:")" || exit 1
sudo rm ~/temp/*.list
sudo minicom -s $chosen
